{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":1,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dfc\/dfcnetworkapierror\/errortype\/unknown"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.deserve.dfc\/documentation\/DFC\/DFCNetworkAPIError\/ErrorType\/unknown","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No overview available."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"title":"DFCNetworkAPIError.ErrorType.unknown","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:3DFC18DFCNetworkAPIErrorV9ErrorTypeO7unknownyA2EmF","modules":[{"name":"DFC"}]},"hierarchy":{"paths":[["doc:\/\/com.deserve.dfc\/documentation\/DFC","doc:\/\/com.deserve.dfc\/documentation\/DFC\/DFCNetworkAPIError","doc:\/\/com.deserve.dfc\/documentation\/DFC\/DFCNetworkAPIError\/ErrorType"]]},"references":{"doc://com.deserve.dfc/documentation/DFC":{"role":"collection","title":"DFC","abstract":[],"identifier":"doc:\/\/com.deserve.dfc\/documentation\/DFC","kind":"symbol","type":"topic","url":"\/documentation\/dfc"},"doc://com.deserve.dfc/documentation/DFC/DFCNetworkAPIError":{"role":"symbol","title":"DFCNetworkAPIError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DFCNetworkAPIError"}],"abstract":[{"type":"text","text":"Enum to hold information about different types of error that may occur during network request."}],"identifier":"doc:\/\/com.deserve.dfc\/documentation\/DFC\/DFCNetworkAPIError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DFCNetworkAPIError"}],"url":"\/documentation\/dfc\/dfcnetworkapierror"},"doc://com.deserve.dfc/documentation/DFC/DFCNetworkAPIError/ErrorType/unknown":{"role":"symbol","title":"DFCNetworkAPIError.ErrorType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[],"identifier":"doc:\/\/com.deserve.dfc\/documentation\/DFC\/DFCNetworkAPIError\/ErrorType\/unknown","kind":"symbol","type":"topic","url":"\/documentation\/dfc\/dfcnetworkapierror\/errortype\/unknown"},"doc://com.deserve.dfc/documentation/DFC/DFCNetworkAPIError/ErrorType":{"role":"symbol","title":"DFCNetworkAPIError.ErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorType"}],"abstract":[],"identifier":"doc:\/\/com.deserve.dfc\/documentation\/DFC\/DFCNetworkAPIError\/ErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorType"}],"url":"\/documentation\/dfc\/dfcnetworkapierror\/errortype"}}}